### ISSUE TITLE
updatesnapyaml.py failing for unknown reason

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#108]
I have a few apps using the action that all should be passing, yet is throwing an exit 1 for some unknown reason.

Examples:
* eog: https://github.com/ubuntu/eog/actions/runs/4961420758/jobs/8878173237
* epiphany: https://github.com/ubuntu/epiphany/actions/runs/4962550881/jobs/8880749407
* evince: https://github.com/ubuntu/evince/actions/runs/4962675911/jobs/8881024036

The common stdout error is:
```
Run ./desktop-snaps/updatesnap/updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/epiphany
Error: Process completed with exit code 1.
```

You can reproduce this locally with:
```
heather@fenrir:~/Projects/snap-automation/desktop-snaps/updatesnap$ ./updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/epiphany.git

heather@fenrir:~/Projects/snap-automation/desktop-snaps/updatesnap$ echo $?
1
```
@sergio-costas could you please take a look at this?

**Comment by rastersoft** [comment]
Can you try with "updatesnap.py" instead? It should print the error...

**Comment by hellsworth** [comment]
```
heather@fenrir:~/Projects/snap-automation/desktop-snaps/updatesnap$ ./updatesnap.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/epiphany.git
Traceback (most recent call last):
  File "/home/heather/Projects/snap-automation/desktop-snaps/updatesnap/./updatesnap.py", line 122, in <module>
    main()
  File "/home/heather/Projects/snap-automation/desktop-snaps/updatesnap/./updatesnap.py", line 116, in main
    data, _ = process_data(response.content.decode('utf-8'), argument_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heather/Projects/snap-automation/desktop-snaps/updatesnap/./updatesnap.py", line 39, in process_data
    snap.load_external_data(data)
  File "/home/heather/Projects/snap-automation/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 453, in load_external_data
    self._open_yaml_file_with_extensions(data, "updatesnap")
  File "/home/heather/Projects/snap-automation/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 499, in _open_yaml_file_with_extensions
    self._config = yaml.safe_load(newfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 28, column 66:
     ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ... 
                                         ^
```

**Comment by rastersoft** [comment]
Odd... the problem is inside the YAML module...

**Comment by hellsworth** [comment]
Interesting. Well here is the [epiphany snapcraft.yaml](https://github.com/ubuntu/epiphany/blob/stable/snapcraft.yaml). Do you see anything wrong with the metadata I've added?

**Comment by sergio-costas** [comment]
Putting the right URI in updatesnap.py does the trick: ./updatesnap.py https://raw.githubusercontent.com/ubuntu/epiphany/stable/snapcraft.yaml

![image](https://github.com/ubuntu/desktop-snaps/assets/105285003/d66142e2-2953-4d53-b524-09e8006bb6dd)

**Comment by hellsworth** [comment]
There were some changes to what updatesnapyaml.py requires and how it handles parts with no source branch or source tag.
