### ISSUE TITLE
updatesnapyaml - string indices must be integers

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#153]
I'm not sure what the issue is with swell-foop but I get a [traceback](https://github.com/ubuntu/swell-foop/actions/runs/5073220850/jobs/9112021956) complaining that string indices must be integers:
```
Run ./desktop-snaps/updatesnap/updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/swell-foop
Traceback (most recent call last):
  File "/home/runner/work/swell-foop/swell-foop/./desktop-snaps/updatesnap/updatesnapyaml.py", line 126, in <module>
    main()
  File "/home/runner/work/swell-foop/swell-foop/./desktop-snaps/updatesnap/updatesnapyaml.py", line 95, in main
    parts, tag_error = snap.process_parts()
  File "/home/runner/work/swell-foop/swell-foop/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 554, in process_parts
    parts.append(self.process_part(part))
  File "/home/runner/work/swell-foop/swell-foop/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 658, in process_part
    if self._checkopt("allow-neither-tag-nor-branch", version_format):
  File "/home/runner/work/swell-foop/swell-foop/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 86, in _checkopt
    return (option in dictionary) and dictionary[option]
TypeError: string indices must be integers
Error: Process completed with exit code 1.
```

**Comment by sergio-costas** [comment]
There is a bug in the YAML file:

![image](https://github.com/ubuntu/desktop-snaps/assets/105285003/ecc6bff8-74ca-448c-9af0-ea14e7cc03cd)

You must put: `allow-neither-tag-nor-branch: true` to ensure that `version-format` is a dictionary.

I'll add a test for that in the code, to return an error in that case.

**Comment by sergio-costas** [comment]
Ok, added a patch that will check for this error.
