### ISSUE TITLE
local installation of the update snap module doesn't work

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/desktop-snaps#219]
The README of the update snap is wrong regarding the installation. 

https://github.com/ubuntu/desktop-snaps/blob/stable/updatesnap/README.md?plain=1#L9

I think it should be `sudo ./install.sh`

Also, when I run `sudo ./install.sh` or `sudo sh install.sh`, I get errors that the updatesnap.py file not found.

```
Traceback (most recent call last):
  File "/home/soumyaxubuntu/Downloads/Project/desktop-snaps/updatesnap/./mix_modules.py", line 50, in <module>
    with open(destination, "w") as ofile:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/updatesnap.py'
Traceback (most recent call last):
  File "/home/soumyaxubuntu/Downloads/Project/desktop-snaps/updatesnap/./mix_modules.py", line 50, in <module>
    with open(destination, "w") as ofile:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/updatesnapyaml.py'
```

**Comment by hellsworth** [comment]
Hmm, I just tried this in an ubuntu 23.04 vm and had no issues running `sudo ./install.sh` but I agree the command in the readme needs the "./" added..

What OS are you on? What is in `/usr/local/bin`?

**Comment by soumyaDghosh** [comment]
I am also on Ubuntu 23.04. But, I didn't have the `/usr/local/bin` folder. I manually created it and it's fixed. I think it should be able to create it by itself.

**Comment by soumyaDghosh** [comment]
Also, there is this another issue, when I am trying to update the webkitgtk-sdk snap, I'm getting this.

https://github.com/soumyaDghosh/webkitgtk-sdk/actions/runs/5487334691/jobs/9998653424#step:3:420

In the api list `webkitgtk-2.40.1` is not there. So, I tried with `2.40.2` again, no luck, this was in the api list BTW. Then I changed the tag to `2.41.0`, and now, it's just getting rate limited. I tried with my own token also, locally. No Luck.

```
Opening file snap/snapcraft.yaml
Part: webkitgtk-6-gnome-2204-sdk (https://github.com/WebKit/WebKit.git)
Asking URI https://api.github.com/repos/WebKit/WebKit/tags?sort=created&directioAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direcAsking URI https://api.github.com/repositories/320636477/tags?sort=created&direc  Current tag: webkitgtk-2.41.0
  Error: can't find the current tag in the tag list.
webkitgtk-6-gnome-2204-sdk: needs version format definition.
```

This one I have tried with my own `github-token`

**Comment by hellsworth** [comment]
> I am also on Ubuntu 23.04. But, I didn't have the `/usr/local/bin` folder. I manually created it and it's fixed. I think it should be able to create it by itself.

well the snap won't have access to the host's `/usr/local/bin` so this is expected to be there. I wonder why you needed to create it though.

As for your other issue finding the tag, I have reproduced it even though the tag is absolutely there. I'm not sure what is happening there so I've opened #223 .

**Comment by sergio-costas** [comment]
Fixed the "/usr/local/bin" problem. It's odd that your system doesn't have it by default...

**Comment by soumyaDghosh** [comment]
Ummm may be I accidentally deleted it during cleanups. Thanks for the fix BTW

**Comment by sergio-costas** [comment]
Or maybe by default it doesn't exist... In theory, it is for user-compiled programs, so...
