### ISSUE TITLE
yaml.reader.ReaderError: unacceptable character #x001b: special characters are not allowed   in "<unicode string>"

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#27]
```
Run ./desktop-snaps/updatesnap/updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/gnome-calculator > snapcraft.yaml
Traceback (most recent call last):
  File "/home/runner/work/gnome-calculator/gnome-calculator/./desktop-snaps/updatesnap/updatesnapyaml.py", line 119, in <module>
    main()
  File "/home/runner/work/gnome-calculator/gnome-calculator/./desktop-snaps/updatesnap/updatesnapyaml.py", line 87, in main
    snap.load_external_data(contents)
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 408, in load_external_data
    self._open_yaml_file_with_extensions(data, "updatesnap")
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 455, in _open_yaml_file_with_extensions
    self._config = yaml.safe_load(newfile)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/lib/python3/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x001b: special characters are not allowed
  in "<unicode string>", position 0
Error: Process completed with exit code 1.
```
@sergio-costas It seems your recent changes somehow is now injecting a `#` causing the updatesnapyaml.py to fail.

**Comment by sergio-costas** [comment]
My fault. Now I changed the "print()"s to make them go to STDERR, leaving only STDOUT for the YAML file.

Also, now it returns 0 if there was an update, or -1 if there was no update, so you can send the output into a temporary file and only overwrite the current snapcraft.yaml file if the output is zero.
