### ISSUE TITLE
updatesnapyaml - sys not defined

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#46]
With the most recent changes to updatesnapyaml.py and it's modules, I re-ran the job for gnome-calculator and seems a module needs to be imported?

https://github.com/ubuntu/gnome-calculator/actions/runs/4692609183/jobs/8318532056#step:8:161

```
Run ./desktop-snaps/updatesnap/updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/gnome-calculator > snapcraft.yaml
Traceback (most recent call last):
  File "/home/runner/work/gnome-calculator/gnome-calculator/./desktop-snaps/updatesnap/updatesnapyaml.py", line 120, in <module>
    main()
  File "/home/runner/work/gnome-calculator/gnome-calculator/./desktop-snaps/updatesnap/updatesnapyaml.py", line 92, in main
    parts = snap.process_parts()
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 497, in process_parts
    parts.append(self.process_part(part))
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 564, in process_part
    tags = self._get_tags(source, current_tag, version_format)
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 480, in _get_tags
    tags = self._gitlab.get_tags(source, current_tag, version_format)
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 352, in get_tags
    data = self._read_pages(tag_command)
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 170, in _read_pages
    self._colors.clear_line()
  File "/home/runner/work/gnome-calculator/gnome-calculator/desktop-snaps/updatesnap/SnapModule/snapmodule.py", line 28, in clear_line
    print(self.clearline, end="\r", file=sys.stderr) # clear the line
NameError: name 'sys' is not defined
Error: Process completed with exit code 1.
```

**Comment by hellsworth** [comment]
Fixed with #47
